Anime.create(name:"Aa! Megami-sama!: Chichaitte Koto wa Benri da ne")
Anime.create(name:"Absolute Duo")
Anime.create(name:"Active Raid: Kidou Kyoushuushitsu Dai Hakkei")
Anime.create(name:"Aggressive Retsuko")
Anime.create(name:"Aikatsu Stars!")
Anime.create(name:"Aikatsu!")
Anime.create(name:"Aishiteruze Baby??")
Anime.create(name:"Ajin")
Anime.create(name:"Akagami no Shirayuki-hime")
Anime.create(name:"Akage no Anne")
Anime.create(name:"Aki Sora")
Anime.create(name:"Aki Sora: Yume no Naka")
Anime.create(name:"Aldnoah.Zero")
Anime.create(name:"All Out!!")
Anime.create(name:"Alps no Shoujo Heidi")
Anime.create(name:"Amaama to Inazuma")
Anime.create(name:"Amagami SS")
Anime.create(name:"Amagi Brilliant Park")
Anime.create(name:"Amanchu!")
Anime.create(name:"Ame-iro Cocoa: Rainy Color e Youkoso!")
Anime.create(name:"Ange Vierge")
Anime.create(name:"Angelique")
Anime.create(name:"Angelique: Shiroi Tsubasa no Memoire")
Anime.create(name:"Ani Tore! EX")
Anime.create(name:"Anne Happy")
Anime.create(name:"Anyamaru Tantei Kiruminzuu")
Anime.create(name:"Ao no Kanata no Four Rhythm")
Anime.create(name:"Ao Oni The Animation")
Anime.create(name:"Aoharu x Kikanjuu")
Anime.create(name:"Aoki Hagane no Arpeggio: Ars Nova Cadenza")
Anime.create(name:"Aoki Hagane no Arpeggio: Ars Nova")
Anime.create(name:"Aquarion Logos")
Anime.create(name:"Aria The Avvenire")
Anime.create(name:"Asa Made Jugyou Chu!")
Anime.create(name:"Asobi ni Iku yo!")
Anime.create(name:"Assassination Classroom (Ansatsu Kyoushitsu)")
Anime.create(name:"Axis Powers Hetalia")
Anime.create(name:"B-Project: Kodou*Ambitious")
Anime.create(name:"Baby Steps")
Anime.create(name:"Baka to Test to Shoukanjuu")
Anime.create(name:"Bakemono no Ko")
Anime.create(name:"Bakemonogatari")
Anime.create(name:"Bakuon!!")
Anime.create(name:"Bananya")
Anime.create(name:"BAR Kiraware Yasai")
Anime.create(name:"Battery")
Anime.create(name:"Battle Spirits: Burning Soul")
Anime.create(name:"Battle Spirits: Double Drive")
Anime.create(name:"Beast Saga")
Anime.create(name:"Bernard-jou Iwaku")
Anime.create(name:"Berserk (2016)")
Anime.create(name:"Beyblade Burst")
Anime.create(name:"Big Order")
Anime.create(name:"Bikini Warriors")
Anime.create(name:"Binan Koukou Chikyuu Bouei-bu LOVE!")
Anime.create(name:"Bishoujo Yuugi Unit Crane Game Girls")
Anime.create(name:"Bleach")
Anime.create(name:"Bloodivores")
Anime.create(name:"Boku dake ga Inai Machi")
Anime.create(name:"Boku no Hero Academia")
Anime.create(name:"Boku No Marie")
Anime.create(name:"Bonjour Sweet Love Patisserie")
Anime.create(name:"Bonobono (2016)")
Anime.create(name:"Brave Beats")
Anime.create(name:"Brave Witches")
Anime.create(name:"Brotherhood: Final Fantasy XV")
Anime.create(name:"Brothers Conflict")
Anime.create(name:"Bubuki Buranki")
Anime.create(name:"Buddy Complex")
Anime.create(name:"Bungou Stray Dogs")
Anime.create(name:"Cardfight!! Vanguard G")
Anime.create(name:"Chaos Dragon: Sekiryuu Seneki")
Anime.create(name:"Charlotte")
Anime.create(name:"Cheating Craft")
Anime.create(name:"Cheer Danshi!!")
Anime.create(name:"Chi's Sweet Home (2016)")
Anime.create(name:"Chousoku Henkei Gyrozetter")
Anime.create(name:"Chrome Shelled Regios")
Anime.create(name:"Chu Feng: B.E.E")
Anime.create(name:"Clannad After Story")
Anime.create(name:"ClassicaLoid")
Anime.create(name:"Classroom Crisis")
Anime.create(name:"Code Geass: Boukoku no Akito")
Anime.create(name:"Coluboccoro")
Anime.create(name:"Comet Lucifer")
Anime.create(name:"Comical Psychosomatic Medicine(Anime de Wakaru Shinryounaika)")
Anime.create(name:"Concrete Revolutio: Choujin Gensou - The Last Song")
Anime.create(name:"Concrete Revolutio: Choujin Gensou")
Anime.create(name:"Crayon Shin-chan Gaiden: Alien vs. Shinnosuke")
Anime.create(name:"Cross Ange: Rondo of Angels and Dragons")
Anime.create(name:"Cupid's Chocolates (Aishen Qiaokeli-ing...)")
Anime.create(name:"Cute High Earth Defense Club LOVE!")
Anime.create(name:"Cutey Honey")
Anime.create(name:"Cyborg 009 VS Devilman")
Anime.create(name:"D.Gray-Man")
Anime.create(name:"D.Gray-man Hallow")
Anime.create(name:"Dagashi Kashi")
Anime.create(name:"Damekko D?butsu")
Anime.create(name:"Dance in the Vampire Bund")
Anime.create(name:"Dance with Devils")
Anime.create(name:"Danchigai")
Anime.create(name:"Danganronpa 3: The End of Kibougamine Gakuen - Kibou-hen")
Anime.create(name:"Danganronpa 3: The End of Kibougamine Gakuen - Mirai-hen")
Anime.create(name:"Danganronpa 3: The End of Kibougamine Gakuen - Zetsubou-hen")
Anime.create(name:"Danna ga Nani wo Itteiru ka Wakaranai Ken (I Can't Understand What My Husband Is Saying)")
Anime.create(name:"Days (TV)")
Anime.create(name:"DD Hokuto no Ken 2 Ichigo Aji+")
Anime.create(name:"Death Billiards")
Anime.create(name:"Death Note (2015)")
Anime.create(name:"Denpa Kyoshi")
Anime.create(name:"Denpa Onna to Seishun Otoko")
Anime.create(name:"Diabolik Lovers More Blood")
Anime.create(name:"Diamond no Ace")
Anime.create(name:"Digimon Adventure Tri. 2: Ketsui")
Anime.create(name:"Digimon Adventure tri. 3: Kokuhaku")
Anime.create(name:"Digimon Adventure Tri.")
Anime.create(name:"Digimon Universe: Appli Monsters")
Anime.create(name:"Dimension W")
Anime.create(name:"Divine Gate")
Anime.create(name:"Doamaiger D")
Anime.create(name:"Dog Days")
Anime.create(name:"Dragon Ball Kai")
Anime.create(name:"Dragon Ball Super")
Anime.create(name:"Dragon Collection")
Anime.create(name:"Dream Festival!")
Anime.create(name:"Drifters")
Anime.create(name:"Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka (Is It Wrong to Try to Pick Up Girls in a Dungeon?) ")
Anime.create(name:"Durarara!!")
Anime.create(name:"Durarara!!x2 Ketsu")
Anime.create(name:"Durarara!!x2 Sho")
Anime.create(name:"Durarara!!x2 Ten")
Anime.create(name:"Early Reins")
Anime.create(name:"Eden of the East")
Anime.create(name:"Elfen Lied")
Anime.create(name:"Endride")
Anime.create(name:"Etotama")
Anime.create(name:"Eve no Jikan")
Anime.create(name:"F-Zero: Falcon Densetsu")
Anime.create(name:"Fairy Tail")
Anime.create(name:"Fate/kaleid liner Prisma Illya 2wei!")
Anime.create(name:"Fate/kaleid liner Prisma Illya 3rei!")
Anime.create(name:"Fate/stay night: Unlimited Blade Works (TV) 2nd Season")
Anime.create(name:"Fate/stay night: Unlimited Blade Works")
Anime.create(name:"Flip Flappers")
Anime.create(name:"Flowering Heart")
Anime.create(name:"Flying Witch")
Anime.create(name:"Flying Witch Petit")
Anime.create(name:"Folktales from Japan")
Anime.create(name:"Food Wars: Shokugeki no Soma")
Anime.create(name:"Fudanshi Koukou Seikatsu")
Anime.create(name:"Fukigen na Mononokean")
Anime.create(name:"Full Moon wo Sagashite")
Anime.create(name:"Fullmetal Alchemist")
Anime.create(name:"Fullmetal Alchemist Brotherhood")
Anime.create(name:"Fune wo Amu")
Anime.create(name:"Fushigi na Somera-chan")
Anime.create(name:"Futsuu no Joshikousei ga [Locodol] Yatte Mita.")
Anime.create(name:"Future Card Buddyfight Hundred")
Anime.create(name:"Future Card Buddyfight Triple D")
Anime.create(name:"Ga-Rei Zero")
Anime.create(name:"Gakkou Gurashi! (School-Live!)")
Anime.create(name:"Gakuen Handsome")
Anime.create(name:"Gakusen Toshi Asterisk")
Anime.create(name:"Galaxy Angel Rune")
Anime.create(name:"Galaxy Angel X")
Anime.create(name:"Gangsta")
Anime.create(name:"Garo: Guren no Tsuki")
Anime.create(name:"Garo: The Animation")
Anime.create(name:"Gatchaman Crowds Insight")
Anime.create(name:"Gate: Jieitai Kanochi nite Kaku Tatakaeri - Enryuu-hen")
Anime.create(name:"Gate: Jieitai Kanochi nite Kaku Tatakaeri")
Anime.create(name:"Gekkan Shoujo Nozaki-kun")
Anime.create(name:"Getsuyoubi no Tawawa")
Anime.create(name:"Ghost in the Shell: Arise - Alternative Architecture")
Anime.create(name:"Gi(a)rlish Number")
Anime.create(name:"Gintama")
Anime.create(name:"Go! Princess PreCure")
Anime.create(name:"Gochuumon wa Usagi Desu ka??")
Anime.create(name:"God Eater")
Anime.create(name:"Grisaia no Kajitsu (The Fruit of Grisaia)")
Anime.create(name:"Grisaia no Rakuen")
Anime.create(name:"Gugure! Kokkuri-san")
Anime.create(name:"Gundam Build Fighters Try")
Anime.create(name:"Gundam Reconguista in G")
Anime.create(name:"Gunslinger Stratos: The Animation")
Anime.create(name:"Gyakuten Saiban: Sono 'Shinjitsu' Igi Ari!")
Anime.create(name:"Hacka Doll The Animation")
Anime.create(name:"Hagane Orchestra")
Anime.create(name:"Hagure Yuusha no Aesthetica")
Anime.create(name:"Hai to Gensou no Grimgar")
Anime.create(name:"Haifuri")
Anime.create(name:"Haikyuu!! Second Season")
Anime.create(name:"Haikyuu!! Third Season")
Anime.create(name:"Haiyore! Nyaruko-san")
Anime.create(name:"Haiyore! Nyaruko-san W")
Anime.create(name:"Haiyoru! Nyaruani")
Anime.create(name:"Haiyoru! Nyaruani: Remember My Love(craft-sensei)")
Anime.create(name:"Hakuouki: Otogisoushi")
Anime.create(name:"Handa-kun")
Anime.create(name:"HappinessCharge PreCure!")
Anime.create(name:"Happy Cooking Graffiti (Koufuku Graffiti)")
Anime.create(name:"Happy?Lesson (TV)")
Anime.create(name:"Happy?Lesson")
Anime.create(name:"Happy?Lesson: Advance")
Anime.create(name:"Happy?Lesson: The Final")
Anime.create(name:"Haruchika: Haruta to Chika wa Seishun Suru")
Anime.create(name:"Hatsukoi Limited")
Anime.create(name:"Hatsukoi Monster")
Anime.create(name:"Hayate no Gotoku")
Anime.create(name:"Heavy Object")
Anime.create(name:"Hentai Ouji to Warawanai Neko")
Anime.create(name:"Hero Bank")
Anime.create(name:"Hetalia: The World Twinkle")
Anime.create(name:"Heybot!")
Anime.create(name:"Hidan no Aria AA")
Anime.create(name:"High School DxD BorN")
Anime.create(name:"High School Star Musical")
Anime.create(name:"Highschool of the Dead")
Anime.create(name:"Higurashi no Naku Koro ni")
Anime.create(name:"Hikaru No Go")
Anime.create(name:"Himouto! Umaru-chan")
Anime.create(name:"Himouto! Umaru-chan S")
Anime.create(name:"Hitori no Shita: The Outcast")
Anime.create(name:"Honobono Log")
Anime.create(name:"Hoozuki no Reitetsu")
Anime.create(name:"Hoshikuzu Paradise")
Anime.create(name:"Hundred")
Anime.create(name:"Ichiban Ushiro no Daimaou")
Anime.create(name:"Idol Memoriese")
Anime.create(name:"Igano Kabamaru")
Anime.create(name:"Imawa no Kuni no Alice")
Anime.create(name:"Inuyasha The Final Act")
Anime.create(name:"Iron Man")
Anime.create(name:"Isekai no Seikishi Monogatari")
Anime.create(name:"Isuca")
Anime.create(name:"Itoshi no Muco")
Anime.create(name:"Jewelpet Sunshine")
Anime.create(name:"Jewelpet: Magical Change")
Anime.create(name:"Jitsu wa Watashi wa")
Anime.create(name:"JK Meshi!")
Anime.create(name:"JoJo no Kimyou na Bouken: Diamond wa Kudakenai")
Anime.create(name:"JoJo's Bizarre Adventure: Stardust Crusaders")
Anime.create(name:"Joker Game")
Anime.create(name:"Joukamachi no Dandelion (Castle Town Dandelion) ")
Anime.create(name:"Junjou Romantica")
Anime.create(name:"K")
Anime.create(name:"K: Return of Kings")
Anime.create(name:"Kagaku na Yatsura")
Anime.create(name:"Kagewani")
Anime.create(name:"Kagewani: Shou")
Anime.create(name:"Kaich? wa Maid-sama!")
Anime.create(name:"Kaijuu Girls: Ultra Kaijuu Gijinka Keikaku")
Anime.create(name:"Kamisama Hajimemashita")
Anime.create(name:"Kamisama Hajimemashita: Kako-hen")
Anime.create(name:"Kamisama Minarai: Himitsu no Cocotama")
Anime.create(name:"Kannagi")
Anime.create(name:"Kanojo to Kanojo no Neko: Everything Flows")
Anime.create(name:"Kantai Collection")
Anime.create(name:"Kare Baka: Wagahai no Kare wa Baka de R")
Anime.create(name:"Kateikyoushi Hitman Reborn")
Anime.create(name:"Kaze no Naka no Shoujo: Kinpatsu no Jeanie")
Anime.create(name:"Keijo!!!!!!!!")
Anime.create(name:"Kekkai Sensen")
Anime.create(name:"Kekkaishi")
Anime.create(name:"Kiitarou Shounen no Youkai Enikki")
Anime.create(name:"Kimi ni Todoke")
Anime.create(name:"Kin-iro Mosaic")
Anime.create(name:"Kindaichi Shounen no Jikenbo Returns 2nd Season")
Anime.create(name:"Kiss x sis")
Anime.create(name:"Kiznaiver")
Anime.create(name:"Kobato")
Anime.create(name:"Kodomo no Jikan")
Anime.create(name:"Koisuru Tenshi Angelique: Kagayaki no Ashita")
Anime.create(name:"Koisuru Tenshi Angelique: Kokoro no Mezameru Toki")
Anime.create(name:"Kokoro ga Sakebitagatterunda")
Anime.create(name:"Kono Bijutsubu ni wa Mondai ga Aru!")
Anime.create(name:"Kono Danshi Uchuujin to Tatakaemasu")
Anime.create(name:"Kono Subarashii Sekai ni Shukufuku wo!")
Anime.create(name:"Koukaku no Pandora")
Anime.create(name:"Koutetsujou no Kabaneri")
Anime.create(name:"Kowabon")
Anime.create(name:"Koyomimonogatari")
Anime.create(name:"Kubikiri Cycle: Aoiro Savant to Zaregototsukai")
Anime.create(name:"Kuma Miko")
Anime.create(name:"Kurayami Santa")
Anime.create(name:"Kuroko’s Basketball")
Anime.create(name:"Kuromukuro")
Anime.create(name:"Kuroshitsuji")
Anime.create(name:"Kuusen Madoushi Kouhosei no Kyoukan (Sky Wizards Academy)")
Anime.create(name:"Kyoukasho ni Nai!")
Anime.create(name:"Kämpfer")
Anime.create(name:"Lady Jewelpet")
Anime.create(name:"Lance N' Masques")
Anime.create(name:"Little Witch Academia: Mahou Shikake no Parade")
Anime.create(name:"Long Riders!")
Anime.create(name:"Lostorage Incited WIXOSS")
Anime.create(name:"Love Live! Sunshine!!")
Anime.create(name:"Lovely?Complex")
Anime.create(name:"Luck & Logic")
Anime.create(name:"Lupin III (2015)")
Anime.create(name:"Macademi Wasshoi!")
Anime.create(name:"Machine-Doll wa Kizutsukanai ")
Anime.create(name:"Macross ?")
Anime.create(name:"Magi: Sinbad no Bouken (TV)")
Anime.create(name:"Magi: Sinbad no Bouken")
Anime.create(name:"Magic Kaito")
Anime.create(name:"Magic Kyun! Renaissance")
Anime.create(name:"Magical Girl Lyrical Nanoha ViVid (Mahou Shoujo Lyrical Nanoha ViVid)")
Anime.create(name:"Maho Girls PreCure!")
Anime.create(name:"Mahou Shoujo Ikusei Keikaku")
Anime.create(name:"Mahou Shoujo Nante Mou Ii Desukara")
Anime.create(name:"Mahou Shoujo? Naria?Girls ")
Anime.create(name:"Majin Bone")
Anime.create(name:"Majokko Megu-chan")
Anime.create(name:"Major")
Anime.create(name:"Maken-ki!")
Anime.create(name:"Maken-Ki! Two")
Anime.create(name:"Makura no Danshi")
Anime.create(name:"MAR")
Anime.create(name:"Maria the Virgin Witch (Junketsu no Maria)")
Anime.create(name:"Maria-sama ga Miteru 3rd")
Anime.create(name:"Maria-sama ga Miteru 4th")
Anime.create(name:"Maria-sama ga Miteru")
Anime.create(name:"Maria-sama ga Miteru: Haru")
Anime.create(name:"Marvel Disk Wars: The Avengers")
Anime.create(name:"Masou Gakuen HxH")
Anime.create(name:"Mayo Chiki!")
Anime.create(name:"Mayoi Neko Overrun!")
Anime.create(name:"Mayoiga")
Anime.create(name:"Mazinger Z")
Anime.create(name:"Mikagura School Suite (Mikagura Gakuen Kumikyoku)")
Anime.create(name:"Military!")
Anime.create(name:"Million Doll")
Anime.create(name:"Miss Monochrome")
Anime.create(name:"Mob Psycho 100")
Anime.create(name:"Mobile Suit Gundam Thunderbolt")
Anime.create(name:"Mobile Suit Gundam Unicorn RE:0096")
Anime.create(name:"Mobile Suit Gundam: Iron-Blooded Orphans")
Anime.create(name:"Mobile Suit Gundam: The Origin")
Anime.create(name:"Momokuri (TV)")
Anime.create(name:"Momokuri")
Anime.create(name:"Monster Hunter Stories: Ride On")
Anime.create(name:"Monster Musume no Iru Nichijou")
Anime.create(name:"Monster Strike")
Anime.create(name:"Motto To LOVE-Ru")
Anime.create(name:"Moyashimon")
Anime.create(name:"Mudazumo Naki Kaikaku")
Anime.create(name:"Musaigen no Phantom World")
Anime.create(name:"Muv-Luv Alternative: Total Eclipse")
Anime.create(name:"My Love Story!! (Ore Monogatari!!)")
Anime.create(name:"Mysterious Joker (Kaitou Joker)")
Anime.create(name:"Nagato Yuki-chan no Shoushitsu")
Anime.create(name:"Nanbaka")
Anime.create(name:"Naruto")
Anime.create(name:"Naruto Shippuden")
Anime.create(name:"Natsu no Arashi! Akinai-chuu")
Anime.create(name:"Natsu no Arashi!")
Anime.create(name:"Nazotokine")
Anime.create(name:"Nejimaki Seirei Senki: Tenkyou no Alderamin")
Anime.create(name:"Neo Angelique Abyss")
Anime.create(name:"Neo Angelique Abyss: Second Age")
Anime.create(name:"Netoge no Yome wa Onnanoko ja Nai to Omotta? ")
Anime.create(name:"New Game!")
Anime.create(name:"Nihon Animator Mihonichi")
Anime.create(name:"Nijiiro Days")
Anime.create(name:"Ninja Slayer From Animation")
Anime.create(name:"Ninku")
Anime.create(name:"Nisekoi")
Anime.create(name:"Noblesse")
Anime.create(name:"Nobunaga no Shinobi")
Anime.create(name:"Noein: Mou Hitori no Kimi e")
Anime.create(name:"Non Non Biyori")
Anime.create(name:"Noragami Aragoto")
Anime.create(name:"Noragami")
Anime.create(name:"Norn9: Norn+Nonet")
Anime.create(name:"Nurarihyon no Mago")
Anime.create(name:"Nurse Witch Komugi-chan Magikarte")
Anime.create(name:"Nurse Witch Komugi-chan Magikarte Z")
Anime.create(name:"Nurse Witch Komugi-chan R")
Anime.create(name:"Nyan Koi")
Anime.create(name:"Nyanbo!")
Anime.create(name:"Occultic;Nine")
Anime.create(name:"Ojisan to Marshmallow")
Anime.create(name:"Okusama ga Seitokaichou!")
Anime.create(name:"Okusama ga Seitokaichou!+!")
Anime.create(name:"Omamori Himari")
Anime.create(name:"Onara Gorou")
Anime.create(name:"One Off")
Anime.create(name:"One Outs")
Anime.create(name:"One Piece")
Anime.create(name:"One Punch Man")
Anime.create(name:"Oneechan ga Kita")
Anime.create(name:"Onigiri")
Anime.create(name:"Onii-chan dakedo Ai Sae Areba Kankeinai yo ne!")
Anime.create(name:"Oniisama e..")
Anime.create(name:"Onsen Yousei Hakone-chan")
Anime.create(name:"Ooyasan wa Shishunki!")
Anime.create(name:"Orange")
Anime.create(name:"Ore ga Ojousama Gakkou ni 'Shomin Sample' Toshite Gets? Sareta Ken")
Anime.create(name:"Oreca Battle")
Anime.create(name:"Oreimo")
Anime.create(name:"Oshiete! Galko-chan")
Anime.create(name:"Oshiri Kajiri Mushi")
Anime.create(name:"Osomatsu-san")
Anime.create(name:"Outbreak Company")
Anime.create(name:"Overlord")
Anime.create(name:"Owari no Seraph")
Anime.create(name:"Owari no Seraph: Nagoya Kessen-hen")
Anime.create(name:"Owarimonogatari")
Anime.create(name:"Ozmafia!!")
Anime.create(name:"Pan de Peace!")
Anime.create(name:"Pandora Hearts")
Anime.create(name:"Papa no Iu Koto o Kikinasai!")
Anime.create(name:"Parasyte -the maxim- (Kiseijuu: Sei no Kakuritsu)")
Anime.create(name:"Peeping Life TV: Season 1??")
Anime.create(name:"Phantasy Star Online 2 The Animation")
Anime.create(name:"Phantom The Animation")
Anime.create(name:"Phantom: Requiem of Phantom")
Anime.create(name:"Planetarian: Chiisana Hoshi no Yume")
Anime.create(name:"Plastic Memories")
Anime.create(name:"Pokemon Sun & Moon")
Anime.create(name:"Pokemon: XY & Z")
Anime.create(name:"Prince of Stride: Alternative")
Anime.create(name:"PriPara")
Anime.create(name:"Prison School")
Anime.create(name:"Punch Line")
Anime.create(name:"Puzzle & Dragons Cross")
Anime.create(name:"Qualidea Code")
Anime.create(name:"R-15")
Anime.create(name:"Ragnastrike Angels")
Anime.create(name:"Rainy Cocoa (Ame-iro Cocoa)")
Anime.create(name:"Rakudai Kishi no Cavalry")
Anime.create(name:"Ranpo Kitan: Game of Laplace")
Anime.create(name:"Re-Kan!")
Anime.create(name:"Re: Cutie Honey")
Anime.create(name:"Re:Petit kara Hajimeru Isekai Seikatsu")
Anime.create(name:"Re:Zero kara Hajimeru Break Time")
Anime.create(name:"Re:Zero kara Hajimeru Isekai Seikatsu")
Anime.create(name:"Regalia: The Three Sacred Stars")
Anime.create(name:"Reikenzan: Hoshikuzu-tachi no Utage")
Anime.create(name:"ReLIFE")
Anime.create(name:"Rewrite")
Anime.create(name:"Rilu Rilu Fairilu: Yousei no Door")
Anime.create(name:"Rin-ne (Kyoukai no Rinne)")
Anime.create(name:"Robot Girls Z")
Anime.create(name:"Robot Town Sagami 2028")
Anime.create(name:"Rokka no Yuusha")
Anime.create(name:"Saekano: How to Raise a Boring Girlfriend (Saenai Heroine no Sodatekata)")
Anime.create(name:"Saijaku Muhai no Bahamut")
Anime.create(name:"Saiki Kusuo no Psi-nan (TV)")
Anime.create(name:"Saiki Kusuo no Psi-nan")
Anime.create(name:"Sailor Moon Crystal")
Anime.create(name:"Saint Seiya: Soul of Gold")
Anime.create(name:"Sakamoto desu ga?")
Anime.create(name:"Saki Biyori")
Anime.create(name:"Sakurako-san no Ashimoto ni wa Shitai ga Umatteiru")
Anime.create(name:"Sakurasou no Pet na Kanojo")
Anime.create(name:"Samurai Warriors (Sengoku Musou)")
Anime.create(name:"Sansha Sanyou")
Anime.create(name:"Sanzoku no Musume Ronja")
Anime.create(name:"Sasami-san@Ganbaranai")
Anime.create(name:"Scared Rider Xechs")
Anime.create(name:"Schwarzesmarken")
Anime.create(name:"Seiken no Blacksmith")
Anime.create(name:"Seiken Tsukai no World Break")
Anime.create(name:"Seikoku no Dragonar")
Anime.create(name:"Seikon no Qwaser")
Anime.create(name:"Seikon no Qwaser II")
Anime.create(name:"Seisen Cerberus: Ryuukoku no Fatalités")
Anime.create(name:"Seitokai Yakuindomo")
Anime.create(name:"Sekirei")
Anime.create(name:"Sekirei: Pure Engagement ")
Anime.create(name:"Sekkou Boys")
Anime.create(name:"Sengoku Choujuu Giga")
Anime.create(name:"Senki Zesshou Symphogear GX")
Anime.create(name:"Servamp")
Anime.create(name:"Seto No Hanayome")
Anime.create(name:"Shakugan no Shana")
Anime.create(name:"Shakunetsu no Takkyuu Musume")
Anime.create(name:"Shimoneta to Iu Gainen ga Sonzai Shinai Taikutsu na Sekai")
Anime.create(name:"Shin Atashin'chi")
Anime.create(name:"Shin Koihime Musou")
Anime.create(name:"Shingeki no Bahamut: Genesis")
Anime.create(name:"Shingeki! Kyojin Chuugakkou")
Anime.create(name:"Shinkyoku Soukai Polyphonica Crimson S")
Anime.create(name:"Shinmai Maou no Testament Burst")
Anime.create(name:"Shinmai Maou no Testament")
Anime.create(name:"Shion no Ou")
Anime.create(name:"Shirobako")
Anime.create(name:"Shisha no Teikoku")
Anime.create(name:"Shoujo-tachi wa Kouya wo Mezasu")
Anime.create(name:"Shounen Ashibe: Go! Go! Goma-chan")
Anime.create(name:"Shounen Hollywood")
Anime.create(name:"Shounen Maid")
Anime.create(name:"Shouwa Genroku Rakugo Shinjuu")
Anime.create(name:"Show By Rock!! #")
Anime.create(name:"Show by Rock!!")
Anime.create(name:"Show By Rock!! Short!!")
Anime.create(name:"Shugo Chara")
Anime.create(name:"Shuumatsu no Izetta")
Anime.create(name:"Sidonia no Kishi (Knights of Sidonia)")
Anime.create(name:"Simoun")
Anime.create(name:"Skip Beat!")
Anime.create(name:"Sore ga Seiyuu!")
Anime.create(name:"Sore ga Seiyuu!: Petit Uchiage")
Anime.create(name:"Soukyuu no Fafner: Dead Aggressor: -EXODUS-")
Anime.create(name:"Soul Buster")
Anime.create(name:"Soul Eater")
Anime.create(name:"Sound! Euphonium (Hibike! Euphonium)")
Anime.create(name:"Sousei no Onmyouji")
Anime.create(name:"Soushin Shoujo Matoi")
Anime.create(name:"Spice and Wolf 2")
Anime.create(name:"Stella no Mahou")
Anime.create(name:"Strike the Blood")
Anime.create(name:"Subete ga F ni Naru: The Perfect Insider")
Anime.create(name:"Super Lovers")
Anime.create(name:"Sushi Police")
Anime.create(name:"Suzakinishi the Animation")
Anime.create(name:"Sword Art Online II: Sword Art Offline II")
Anime.create(name:"Tabi Machi Late Show")
Anime.create(name:"Taboo Tattoo")
Anime.create(name:"Taimadou Gakuen 35 Shiken Shoutai")
Anime.create(name:"Takamiya Nasuno Desu!: Teekyuu Spin-off")
Anime.create(name:"Tales of Zestiria the X ")
Anime.create(name:"Tanaka-kun wa Itsumo Kedaruge")
Anime.create(name:"Tanaka-kun wa Kyou mo Kedaruge")
Anime.create(name:"Tantei Kageki Milky Holmes TD ")
Anime.create(name:"Tantei Team KZ Jiken Note")
Anime.create(name:"Teekyuu")
Anime.create(name:"Tegami Bachi")
Anime.create(name:"Tenshi na Konamaiki")
Anime.create(name:"Tentai Senshi Sunred 2")
Anime.create(name:"Tentai Senshi Sunred")
Anime.create(name:"Terra Formars ")
Anime.create(name:"Terra Formars Revenge")
Anime.create(name:"Tesagure! Bukatsumono Spin-off Purupurun Sharumu to Asobou")
Anime.create(name:"Tetsu no Ryuukihei")
Anime.create(name:"The Heroic Legend of Arslan (Arslan Senki)")
Anime.create(name:"The Idolmaster Cinderella Girls")
Anime.create(name:"The Legend of the Legendary Heroes")
Anime.create(name:"The Rolling Girls")
Anime.create(name:"The Seven Deadly Sins(Nanatsu no Taizai)")
Anime.create(name:"Thunderbolt Fantasy")
Anime.create(name:"Tiger Mask W")
Anime.create(name:"Time Bokan 24")
Anime.create(name:"Time Travel Shoujo: Mari Waka to 8-nin no Kagakusha-tachi")
Anime.create(name:"To Aru Kagaku no Railgun")
Anime.create(name:"To Be Hero")
Anime.create(name:"To Heart 2 AD")
Anime.create(name:"To Heart 2 AD Plus")
Anime.create(name:"To Heart 2 Adnext")
Anime.create(name:"To Heart 2")
Anime.create(name:"To Heart 2: Dungeon Travelers")
Anime.create(name:"To Heart")
Anime.create(name:"To Heart: Remember My Memories")
Anime.create(name:"To LOVE-Ru Darkness 2nd")
Anime.create(name:"To LOVE-Ru Darkness")
Anime.create(name:"To Love-Ru")
Anime.create(name:"Tokyo ESP")
Anime.create(name:"Tokyo Ghoul")
Anime.create(name:"Tokyo Mew Mew")
Anime.create(name:"Tonari no Seki-kun")
Anime.create(name:"Tonkatsu DJ Agetarou")
Anime.create(name:"Toradora!")
Anime.create(name:"Touken Ranbu: Hanamaru")
Anime.create(name:"Triage X")
Anime.create(name:"Tribe Cool Crew")
Anime.create(name:"Trickster: Edogawa Ranpo 'Shounen Tanteidan' yori")
Anime.create(name:"True Tears")
Anime.create(name:"Tsukiuta. The Animation")
Anime.create(name:"Uchuu Patrol Luluco")
Anime.create(name:"Udon no Kuni no Kiniro Kemari")
Anime.create(name:"UFO Gakuen no Himitsu")
Anime.create(name:"Umineko no Naku Koro ni")
Anime.create(name:"Under the Dog")
Anime.create(name:"Unlimited Fafnir (Juuou Mujin no Fafnir)")
Anime.create(name:"Urawa no Usagi-chan")
Anime.create(name:"Usakame")
Anime.create(name:"Ushio to Tora")
Anime.create(name:"Uta no Prince-sama")
Anime.create(name:"Utawarerumono: Itsuwari no Kamen")
Anime.create(name:"Valkyria Chronicles")
Anime.create(name:"Valkyrie Drive: Mermaid")
Anime.create(name:"Vampire Holmes")
Anime.create(name:"Vampire Knight")
Anime.create(name:"Vampire Knight Guilty")
Anime.create(name:"Vandread")
Anime.create(name:"Venus Project: Climax")
Anime.create(name:"ViVid Strike!")
Anime.create(name:"Wagamama High Spec")
Anime.create(name:"Wakaba Girl")
Anime.create(name:"Wakako-zake")
Anime.create(name:"Wake Up Girl Zoo!")
Anime.create(name:"Wake Up Girls!")
Anime.create(name:"Wake Up Girls! Seishun no Kage")
Anime.create(name:"Walkure Romanze")
Anime.create(name:"Watashi ga Motete Dousunda")
Anime.create(name:"Weiß Survive")
Anime.create(name:"Weiß Survive R")
Anime.create(name:"Wish Upon the Pleiades (Houkago no Pleiades)")
Anime.create(name:"Witch Hunter Robin")
Anime.create(name:"Wooser's Hand-to-Mouth Life: Mugen-hen")
Anime.create(name:"Working!!! (Wagnaria!!!)")
Anime.create(name:"World Trigger")
Anime.create(name:"WWW.Working!!")
Anime.create(name:"Yahari Ore no Seishun Love Come wa Machigatteiru (My Teen Romantic Comedy SNAFU)")
Anime.create(name:"Yamada-kun to 7-nin no Majo (Yamada-kun and the Seven Witches)")
Anime.create(name:"Yamato Nadeshiko Shichi Henge ")
Anime.create(name:"Yami Shibai")
Anime.create(name:"Yaoguai Mingdan")
Anime.create(name:"Yatterman Night (Yoru no Yatterman)")
Anime.create(name:"Yona of the Dawn")
Anime.create(name:"Youkai Watch")
Anime.create(name:"Young Black Jack")
Anime.create(name:"Your Lie in April(Shigatsu wa Kimi no Uso)")
Anime.create(name:"Yowamushi Pedal")
Anime.create(name:"Yu-Gi-Oh! 5D`s")
Anime.create(name:"Yu-Gi-Oh! Arc-V")
Anime.create(name:"Yumeiro Patissiere")
Anime.create(name:"Yumeiro Pâtissière SP Professional")
Anime.create(name:"Yuri Yuri")
Anime.create(name:"Yuri!!! on Ice")
Anime.create(name:"Yurikuma Arashi")
Anime.create(name:"Yuru Yuri San?Hai!")
Anime.create(name:"Yuru Yuri??")
Anime.create(name:"Zetsuen no Tempest")
Anime.create(name:"Zettai Bouei Leviathan")
